services:
  web:
    build: ./web
    ports:
      - "9999:80"
    volumes:
      - ./web:/var/www/html
    environment:
      - FLAG=CTF{PRIV_ESC_VIA_INSECURE_DESIGN}
    restart: unless-stopped

  # Optional database service if needed for extension
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: ctf
  #     MYSQL_USER: ctf
  #     MYSQL_PASSWORD: ctf
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql

# volumes:
#   db_data: